token_authentication:
    path:     /token-authentication
    defaults: { _controller: APICoreBundle:Login:tokenAuthentication }
    methods: [POST]

api_users:
    resource: "@APICoreBundle/Resources/config/routing/user.yml"
    prefix: /

api_companies:
    resource: "@APICoreBundle/Resources/config/routing/company.yml"
    prefix: /