token_authentication:
    path:     /token-authentication
    defaults: { _controller: APICoreBundle:Login:tokenAuthentication }
    methods: [POST]

users_list:
    path:     /users
    defaults: { _controller: APICoreBundle:User:listUsers }
    methods: [GET]

user:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:getUser }
    methods: [GET]

user_create:
    path:     /users
    defaults: { _controller: APICoreBundle:User:createUser }
    methods: [POST]

user_update:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:updateUser }
    methods: [PUT]

user_partial_update:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:updatePartialUser }
    methods: [PATCH]

user_delete:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:deleteUser }
    methods: [DELETE]

tags_list:
    path:     /tags
    defaults: { _controller: APICoreBundle:Tag:listTags }
    methods: [GET]

tag:
    path:     /tags/{id}
    defaults: { _controller: APICoreBundle:Tag:getTag }
    methods: [GET]

tag_create:
    path:     /tags
    defaults: { _controller: APICoreBundle:Tag:createTag }
    methods: [POST]

tag_update:
    path:     /tags/{id}
    defaults: { _controller: APICoreBundle:Tag:updateTag }
    methods: [PUT]

tag_partial_update:
    path:     /tags/{id}
    defaults: { _controller: APICoreBundle:Tag:updatePartialTag }
    methods: [PATCH]

tag_delete:
    path:     /tags/{id}
    defaults: { _controller: APICoreBundle:Tag:deleteTag }
    methods: [DELETE]