token_authentication:
    path:     /token-authentication
    defaults: { _controller: APICoreBundle:Login:tokenAuthentication }
    methods: [POST]

users_list:
    path:     /users
    defaults: { _controller: APICoreBundle:User:list }
    methods: [GET]

user:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:get }
    methods: [GET]

user_create:
    path:     /users
    defaults: { _controller: APICoreBundle:User:create }
    methods: [POST]

user_update:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:update }
    methods: [PUT]

user_partial_update:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:updatePartial }
    methods: [PATCH]

user_delete:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:delete }
    methods: [DELETE]

tag_list:
    path:     /tags
    defaults: { _controller: APICoreBundle:Tag:list }
    methods: [GET]

tag:
    path:     /tags/{id}
    defaults: { _controller: APICoreBundle:Tag:get }
    methods: [GET]

tag_create:
    path:     /tags
    defaults: { _controller: APICoreBundle:Tag:create }
    methods: [POST]

tag_update:
    path:     /tags/{id}
    defaults: { _controller: APICoreBundle:Tag:update }
    methods: [PUT]

tag_partial_update:
    path:     /tags/{id}
    defaults: { _controller: APICoreBundle:Tag:updatePartial }
    methods: [PATCH]

tag_delete:
    path:     /tags/{id}
    defaults: { _controller: APICoreBundle:Tag:delete }
    methods: [DELETE]