token_authentication:
    path:     /token-authentication
    defaults: { _controller: APICoreBundle:Login:tokenAuthentication }
    methods: [POST]

users_list:
    path:     /users
    defaults: { _controller: APICoreBundle:User:list }
    methods: [GET]

user:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:get }
    methods: [GET]

user_create:
    path:     /users
    defaults: { _controller: APICoreBundle:User:create }
    methods: [POST]

user_update:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:update }
    methods: [PUT]

user_partial_update:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:updatePartial }
    methods: [PATCH]

user_delete:
    path:     /users/{id}
    defaults: { _controller: APICoreBundle:User:delete }
    methods: [DELETE]

file_upload:
    path:     /upload
    defaults: { _controller: APICoreBundle:Cdn:upload }
    methods: [POST]

file_load:
    path:     /load/{slug}
    defaults: { _controller: APICoreBundle:Cdn:load }
    methods: [GET]