token_authentication:
    path:     /token-authentication
    defaults: { _controller: APICoreBundle:Login:tokenAuthentication }
    methods: [POST]

api_user:
    resource: "@APICoreBundle/Resources/config/routing/user.yml"
    prefix: /users