api_users:
    resource: "@APICoreBundle/Resources/config/routing/user.yml"
api_cdn:
    resource: "@APICoreBundle/Resources/config/routing/cdn.yml"
api_companies:
    resource: "@APICoreBundle/Resources/config/routing/company.yml"

