services:
    api_base.service:
          class: API\CoreBundle\Services\ApiBaseService
          arguments: ["@router"]
    api_user.service:
          class: API\CoreBundle\Services\UserService
          arguments: ["@doctrine.orm.entity_manager","@router"]
          lazy: true
    entity_processor:
        class: API\CoreBundle\Services\ProcessEntity
        arguments: ["@doctrine.orm.default_entity_manager", "@validator"]
        lazy: true
    user_voter:
        class: API\CoreBundle\Security\UserVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
        lazy: true
    upload_helper:
        class: API\CoreBundle\Services\UploadHelper
        arguments: ["%upload_dir%","@doctrine.orm.entity_manager"]

