services:
    api_base.model:
        class: API\CoreBundle\Model\BaseModel
        arguments: ["@doctrine.dbal.default_connection"]
        lazy: true
    api_user.model:
        class: API\CoreBundle\Model\UserModel
        arguments: ["@doctrine.dbal.default_connection", "@router","@jms_serializer"]
        lazy: true
    entity_processor:
        class: API\CoreBundle\Services\ProcessEntity
        arguments: ["@doctrine.orm.default_entity_manager", "@validator"]
        lazy: true
