services:
    api_base.model:
        class: API\CoreBundle\Model\BaseModel
        arguments: ["@doctrine.dbal.default_connection"]
        lazy: true
    api_user.model:
        class: API\CoreBundle\Model\UserModel
        arguments: ["@doctrine.dbal.default_connection", "@router"]
        lazy: true
    api_user.service:
          class: API\CoreBundle\Services\UserService
          arguments: ["@doctrine.orm.entity_manager","@router"]
          lazy: true
    entity_processor:
        class: API\CoreBundle\Services\ProcessEntity
        arguments: ["@doctrine.orm.default_entity_manager", "@validator"]
        lazy: true
    user_voter:
        class: API\CoreBundle\Security\UserVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
        lazy: true
    api_tag.model:
        class: API\CoreBundle\Model\TagModel
        arguments: ["@doctrine.dbal.default_connection", "@router"]
        lazy: true
