services:
    api_base.model:
        class: API\CoreBundle\Model\BaseModel
        arguments: ["@doctrine.dbal.default_connection"]
    api_user.model:
        class: API\CoreBundle\Model\UserModel
        arguments: ["@doctrine.dbal.default_connection"]
