api_task_task:
    resource: "@APITaskBundle/Resources/config/routing/task.yml"
    prefix: /
api_task_tag:
    resource: "@APITaskBundle/Resources/config/routing/tag.yml"
    prefix: /
api_task_status:
    resource: "@APITaskBundle/Resources/config/routing/status.yml"
    prefix: /
api_task_company_attribute:
    resource: "@APITaskBundle/Resources/config/routing/companyAttribute.yml"
    prefix: /
api_task_company_data:
    resource: "@APITaskBundle/Resources/config/routing/companyData.yml"
    prefix: /
