api_task_task:
    resource: "@APITaskBundle/Resources/config/routing/task.yml"
    prefix: /
api_task_tag:
    resource: "@APITaskBundle/Resources/config/routing/tag.yml"
    prefix: /
api_task_status:
    resource: "@APITaskBundle/Resources/config/routing/status.yml"
    prefix: /
api_task_company_attribute:
    resource: "@APITaskBundle/Resources/config/routing/companyAttribute.yml"
    prefix: /
api_task_project:
    resource: "@APITaskBundle/Resources/config/routing/project.yml"
    prefix: /
api_task_task_attribute:
    resource: "@APITaskBundle/Resources/config/routing/taskAttribute.yml"
    prefix: /
api_task_filter:
    resource: "@APITaskBundle/Resources/config/routing/filter.yml"
    prefix: /
api_task_user_role:
    resource: "@APITaskBundle/Resources/config/routing/userRole.yml"
    prefix: /
api_task_unit:
    resource: "@APITaskBundle/Resources/config/routing/unit.yml"
    prefix: /
api_task_invoiceable_item:
    resource: "@APITaskBundle/Resources/config/routing/invoiceableItem.yml"
    prefix: /
api_task_smtp:
    resource: "@APITaskBundle/Resources/config/routing/smtp.yml"
    prefix: /
