services:
    variable_helper:
        class: API\TaskBundle\Services\VariableHelper
    acl_helper:
        class: API\TaskBundle\Services\AclHelper
        arguments: ["@doctrine.orm.entity_manager","@security.access.decision_manager","@security.token_storage"]
    email_service:
        class: API\TaskBundle\Services\EmailService
        arguments: ["@twig","@mailer", "@doctrine.orm.entity_manager"]
    tag_voter:
        class: API\TaskBundle\Security\TagVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    project_voter:
        class: API\TaskBundle\Security\ProjectVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    filter_voter:
        class: API\TaskBundle\Security\FilterVoter
        arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    project_service:
          class: API\TaskBundle\Services\ProjectService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_attribute_service:
          class: API\TaskBundle\Services\TaskAttributeService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_voter:
          class: API\TaskBundle\Security\TaskVoter
          arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    task_service:
          class: API\TaskBundle\Services\TaskService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_additional_service:
          class: API\TaskBundle\Services\TaskAdditionalService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    filter_service:
          class: API\TaskBundle\Services\FilterService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    user_role_service:
          class: API\TaskBundle\Services\UserRoleService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    company_attribute_service:
            class: API\TaskBundle\Services\CompanyAttributeService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    status_service:
            class: API\TaskBundle\Services\StatusService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    tag_service:
            class: API\TaskBundle\Services\TagService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    unit_service:
            class: API\TaskBundle\Services\UnitService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    invoiceable_item_service:
            class: API\TaskBundle\Services\InvoiceableItemService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    smtp_service:
            class: API\TaskBundle\Services\SmtpService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    imap_service:
            class: API\TaskBundle\Services\ImapService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    system_settings_service:
            class: API\TaskBundle\Services\SystemSettingsService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    notifications_service:
            class: API\TaskBundle\Services\NotificationService
            arguments: ["@doctrine.orm.entity_manager", "@router"]