services:
    variable_helper:
        class: API\TaskBundle\Services\VariableHelper
    tag_voter:
        class: API\TaskBundle\Security\TagVoter
        arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    status_voter:
        class: API\TaskBundle\Security\StatusVoter
        arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    company_attribute_voter:
        class: API\TaskBundle\Security\CompanyAttributeVoter
        arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    project_voter:
        class: API\TaskBundle\Security\ProjectVoter
        arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    company_service:
          class: API\TaskBundle\Services\CompanyService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    project_service:
          class: API\TaskBundle\Services\ProjectService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_attribute_voter:
          class: API\TaskBundle\Security\TaskAttributeVoter
          arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    task_attribute_service:
          class: API\TaskBundle\Services\TaskAttributeService
          arguments: ["@doctrine.orm.entity_manager", "@router"]