services:
    variable_helper:
        class: API\TaskBundle\Services\VariableHelper
    tag_voter:
        class: API\TaskBundle\Security\TagVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    status_voter:
        class: API\TaskBundle\Security\StatusVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    company_attribute_voter:
        class: API\TaskBundle\Security\CompanyAttributeVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    project_voter:
        class: API\TaskBundle\Security\ProjectVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    company_service:
          class: API\TaskBundle\Services\CompanyService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    project_service:
          class: API\TaskBundle\Services\ProjectService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_attribute_voter:
          class: API\TaskBundle\Security\TaskAttributeVoter
          arguments: ["@security.access.decision_manager","@security.token_storage"]
    task_attribute_service:
          class: API\TaskBundle\Services\TaskAttributeService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_voter:
          class: API\TaskBundle\Security\TaskVoter
          arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    task_service:
          class: API\TaskBundle\Services\TaskService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_additional_service:
          class: API\TaskBundle\Services\TaskAdditionalService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    filter_service:
              class: API\TaskBundle\Services\FilterService
              arguments: ["@doctrine.orm.entity_manager", "@router"]