services:
    variable_helper:
        class: API\TaskBundle\Services\VariableHelper
    acl_helper:
        class: API\TaskBundle\Services\AclHelper
        arguments: ["@doctrine.orm.entity_manager","@security.access.decision_manager","@security.token_storage"]
    email_service:
        class: API\TaskBundle\Services\EmailService
        arguments: ["@twig","@mailer", "@doctrine.orm.entity_manager"]
    tag_voter:
        class: API\TaskBundle\Security\TagVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    project_voter:
        class: API\TaskBundle\Security\ProjectVoter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    filter_voter:
        class: API\TaskBundle\Security\Filter\Voter
        arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    repeating_task_voter:
        class: API\TaskBundle\Security\RepeatingTask\Voter
        arguments: ["@security.access.decision_manager","@security.token_storage"]
    project_service:
          class: API\TaskBundle\Services\ProjectService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_attribute_service:
          class: API\TaskBundle\Services\TaskAttributeService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_voter:
          class: API\TaskBundle\Security\TaskVoter
          arguments: ["@security.access.decision_manager","@security.token_storage", "@doctrine.orm.entity_manager"]
    task_service:
          class: API\TaskBundle\Services\TaskService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    task_additional_service:
          class: API\TaskBundle\Services\TaskAdditionalService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    filter_get_service:
          class: API\TaskBundle\Services\Filter\GetMethods
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    filter_create_service:
          class: API\TaskBundle\Services\Filter\CreateMethods
          arguments: ["@doctrine.orm.entity_manager"]
    filter_update_service:
          class: API\TaskBundle\Services\Filter\UpdateMethods
          arguments: ["@doctrine.orm.entity_manager"]
    user_role_service:
          class: API\TaskBundle\Services\UserRoleService
          arguments: ["@doctrine.orm.entity_manager", "@router"]
    company_attribute_service:
            class: API\TaskBundle\Services\CompanyAttributeService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    status_service:
            class: API\TaskBundle\Services\StatusService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    tag_service:
            class: API\TaskBundle\Services\TagService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    unit_service:
            class: API\TaskBundle\Services\UnitService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    invoiceable_item_service:
            class: API\TaskBundle\Services\InvoiceableItemService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    smtp_service:
            class: API\TaskBundle\Services\SmtpService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    imap_service:
            class: API\TaskBundle\Services\ImapService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    system_settings_service:
            class: API\TaskBundle\Services\SystemSettingsService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    notifications_service:
            class: API\TaskBundle\Services\NotificationService
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    repeating_task_get_service:
            class: API\TaskBundle\Services\RepeatingTask\GetMethods
            arguments: ["@doctrine.orm.entity_manager", "@router"]
    repeating_task_update_service:
            class: API\TaskBundle\Services\RepeatingTask\UpdateMethods
            arguments: ["@doctrine.orm.entity_manager"]
    repeating_task_cron_service:
            class: API\TaskBundle\Services\RepeatingTask\CronMethods
            arguments: ["@doctrine.orm.entity_manager"]