api_task:
    resource: "@APITaskBundle/Resources/config/routing.yml"
    prefix:   /api/v1/tasks

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /v1/doc
api_core:
    resource: "@APICoreBundle/Resources/config/routing.yml"
    prefix:   /api/v1

