file_upload:
    path:     /cdn/upload
    defaults: { _controller: APICoreBundle:Cdn:upload }
    methods: [POST]

file_upload_image:
    path:     /cdn/upload-image
    defaults: { _controller: APICoreBundle:Cdn:uploadImage }
    methods: [POST]

file_load:
    path:     /cdn/load/{slug}
    defaults: { _controller: APICoreBundle:Cdn:load }
    methods: [GET]

