file_upload:
    path:     /cdn/upload
    defaults: { _controller: APICoreBundle:Cdn:upload }
    methods: [POST]

file_upload_image:
    path:     /cdn/upload-image
    defaults: { _controller: APICoreBundle:Cdn:uploadImage }
    methods: [POST]

file_load_image:
    path:     /cdn/{slug}/load-image
    defaults: { _controller: APICoreBundle:Cdn:loadImage }
    methods: [GET]
    requirements:

