company_list:
    path:     companies
    defaults: { _controller: APICoreBundle:Company:list }
    methods: [GET]

company:
    path:     companies/{id}
    defaults: { _controller: APICoreBundle:Company:get }
    methods: [GET]
    requirements:
        id: '\d+'

company_create:
    path:     companies
    defaults: { _controller: APICoreBundle:Company:create }
    methods: [POST]

company_update:
    path:     companies/{id}
    defaults: { _controller: APICoreBundle:Company:update }
    methods: [PUT]
    requirements:
        id: '\d+'

company_partial_update:
    path:     companies/{id}
    defaults: { _controller: APICoreBundle:Company:updatePartial }
    methods: [PATCH]
    requirements:
        id: '\d+'

company_delete:
    path:     companies/{id}
    defaults: { _controller: APICoreBundle:Company:delete }
    methods: [DELETE]
    requirements:
        id: '\d+'

company_restore:
    path:     companies/restore/{id}
    defaults: { _controller: APICoreBundle:Company:restore }
    methods: [PATCH]
    requirements:
        id: '\d+'

company_search:
    path:     companies/search
    defaults: { _controller: APICoreBundle:Company:search }
    methods: [GET]
