company_list:
    path:     companies
    defaults: { _controller: APICoreBundle:Company:list }
    methods: [GET]

company_search:
    path:     companies/search
    defaults: { _controller: APICoreBundle:Company:search }
    methods: [GET]

company_list_of_all_active:
    path:     companies/all
    defaults: { _controller: APICoreBundle:Company:listOfAllCompanies }
    methods: [GET]

company_list_of_all_active_from_date:
    path:     companies/all/{date}
    defaults: { _controller: APICoreBundle:Company:listOfAllCompanies }
    methods: [GET]
    requirements:
            date: '\d+'

company:
    path:     companies/{id}
    defaults: { _controller: APICoreBundle:Company:get }
    methods: [GET]
    requirements:
        id: '\d+'

company_create:
    path:     companies
    defaults: { _controller: APICoreBundle:Company:create }
    methods: [POST]

company_update:
    path:     companies/{id}
    defaults: { _controller: APICoreBundle:Company:update }
    methods: [PUT]
    requirements:
        id: '\d+'

company_delete:
    path:     companies/{id}/inactivate
    defaults: { _controller: APICoreBundle:Company:delete }
    methods: [PUT]
    requirements:
        id: '\d+'

company_restore:
    path:     companies/{id}/restore
    defaults: { _controller: APICoreBundle:Company:restore }
    methods: [PUT]
    requirements:
        id: '\d+'
