users_list:
    path:     /
    defaults: { _controller: APICoreBundle:User:list }
    methods: [GET]

user:
    path:     /{id}
    defaults: { _controller: APICoreBundle:User:get }
    methods: [GET]
    requirements:
        id: '\d+'

user_create:
    path:     /
    defaults: { _controller: APICoreBundle:User:create }
    methods: [POST]

user_update:
    path:     /{id}
    defaults: { _controller: APICoreBundle:User:update }
    methods: [PUT]
    requirements:
        id: '\d+'

user_partial_update:
    path:     /{id}
    defaults: { _controller: APICoreBundle:User:updatePartial }
    methods: [PATCH]
    requirements:
        id: '\d+'

user_delete:
    path:     /{id}
    defaults: { _controller: APICoreBundle:User:delete }
    methods: [DELETE]
    requirements:
        id: '\d+'