<?php

namespace API\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Traits\CompanyRepositoryTrait;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository implements RepositoryInterface
{
    const LIMIT = 10;

    use CompanyRepositoryTrait;

    /**
     * Return all entities with specific conditions based on actual Entity
     *
     * @param int $page
     *
     * @param array $options
     *
     * @return mixed
     */
    public function getAllEntities(int $page, array $options = [])
    {
        $query = $this->createQueryBuilder('c')
            ->select('c,companyData, companyAttribute')
            ->leftJoin('c.companyData', 'companyData')
            ->leftJoin('companyData.companyAttribute', 'companyAttribute')
            ->getQuery();

        $query->setMaxResults(self::LIMIT);

        /**
         * Pagination calculating offset
         */
        if (1 < $page) {
            $query->setFirstResult(self::LIMIT * $page - self::LIMIT);
        }

        return $query->getArrayResult();
    }

    /**
     * Return one full entity
     *
     * @return mixed
     */
    public function getEntity(int $id)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c,companyData, companyAttribute')
            ->leftJoin('c.companyData', 'companyData')
            ->leftJoin('companyData.companyAttribute', 'companyAttribute')
            ->where('c.id = :companyId')
            ->setParameter('companyId', $id)
            ->getQuery();

        return $query->getArrayResult();
    }

    /**
     * Return count of all Entities
     *
     * @param mixed $options
     *
     * @return int
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \Doctrine\ORM\NoResultException
     */
    public function countEntities(array $options = [])
    {
        $query = $this->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->getQuery()
            ->getSingleScalarResult();

        return $query;
    }
}
