<?php

namespace API\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    const LIMIT = 10;

    /**
     * Return all companies
     *
     * @param int $page
     * @return array
     */
    public function getAllCompanies(int $page)
    {
        $query = $this->createQueryBuilder('c')
            ->getQuery();

        $query->setMaxResults(self::LIMIT);

        /**
         * Pagination calculating offset
         */
        if (1 < $page) {
            $query->setFirstResult(self::LIMIT * $page - self::LIMIT);
        }

        return $query->getArrayResult();
    }

    /**
     * Return count of all companies
     *
     * @return mixed
     */
    public function countCompanies()
    {
        $query = $this->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->getQuery()
            ->getSingleScalarResult();

        return $query;
    }
}
