<?php

namespace API\CoreBundle\Repository;

/**
 * UserAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
