<?php

namespace API\CoreBundle\Repository;

/**
 * UserDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDataRepository extends \Doctrine\ORM\EntityRepository
{
}
