taks_comments_list:
    path:     /comments/task/{taskId}
    defaults: { _controller: APITaskBundle:Comment:tasksList }
    methods: [GET]
    requirements:
            taskId: '\d+'

comment:
    path:     /comments/{id}
    defaults: { _controller: APITaskBundle:Comment:get }
    methods: [GET]
    requirements:
            id: '\d+'

task_tasks_comment_create:
    path:     /comments/task/{taskId}
    defaults: { _controller: APITaskBundle:Comment:createTasksComment }
    methods: [POST]
    requirements:
            taskId: '\d+'

task_comments_comment_create:
    path:     /comments/comment/{commentId}
    defaults: { _controller: APITaskBundle:Comment:createCommentsComment }
    methods: [POST]
    requirements:
            commentId: '\d+'

comment_update:
    path:     /comments/{id}
    defaults: { _controller: APITaskBundle:Comment:update }
    methods: [PUT]
    requirements:
            id: '\d+'

comment_partial_update:
    path:     /comments/{id}
    defaults: { _controller: APITaskBundle:Comment:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

comments_delete:
    path:     /comments/{id}
    defaults: { _controller: APITaskBundle:Comment:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'