company_data_list:
    path:     /company-data/company/{companyId}/company-attribute/{companyAttributeId}
    defaults: { _controller: APITaskBundle:CompanyData:list }
    methods: [GET]

company_data:
    path:     /company-data/{id}
    defaults: { _controller: APITaskBundle:CompanyData:get }
    methods: [GET]
    requirements:
        id: '\d+'

company_data_create:
    path:     /company-data/company/{companyId}/company-attribute/{companyAttributeId}
    defaults: { _controller: APITaskBundle:CompanyData:create }
    methods: [POST]

company_data_update:
    path:     /company-data/{id}
    defaults: { _controller: APITaskBundle:CompanyData:update }
    methods: [PUT]
    requirements:
            id: '\d+'

company_data_partial_update:
    path:     /company-data/{id}
    defaults: { _controller: APITaskBundle:CompanyData:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

company_data_delete:
    path:     /company-data/{id}
    defaults: { _controller: APITaskBundle:CompanyData:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'