company_attribute_list:
    path:     /company-attributes
    defaults: { _controller: APITaskBundle:CompanyAttribute:list }
    methods: [GET]

company_attributes:
    path:     /company-attributes/{id}
    defaults: { _controller: APITaskBundle:CompanyAttribute:get }
    methods: [GET]
    requirements:
        id: '\d+'

company_attribute_create:
    path:     /company-attributes
    defaults: { _controller: APITaskBundle:CompanyAttribute:create }
    methods: [POST]

company_attribute_update:
    path:     /company-attributes/{id}
    defaults: { _controller: APITaskBundle:CompanyAttribute:update }
    methods: [PUT]
    requirements:
            id: '\d+'

company_attribute_inactivate:
    path:     /company-attributes/{id}/inactivate
    defaults: { _controller: APITaskBundle:CompanyAttribute:delete }
    methods: [PUT]
    requirements:
            id: '\d+'

company_attribute_restore:
    path:     /company-attributes/{id}/restore
    defaults: { _controller: APITaskBundle:CompanyAttribute:restore }
    methods: [PUT]
    requirements:
            id: '\d+'