company_attribute_list:
    path:     /company-attributes
    defaults: { _controller: APITaskBundle:CompanyAttribute:list }
    methods: [GET]

company_attributes:
    path:     /company-attributes/{id}
    defaults: { _controller: APITaskBundle:CompanyAttribute:get }
    methods: [GET]
    requirements:
        id: '\d+'

company_attribute_create:
    path:     /company-attributes
    defaults: { _controller: APITaskBundle:CompanyAttribute:create }
    methods: [POST]

company_attribute_update:
    path:     /company-attributes/{id}
    defaults: { _controller: APITaskBundle:CompanyAttribute:update }
    methods: [PUT]
    requirements:
            id: '\d+'

company_attribute_partial_update:
    path:     /company-attributes/{id}
    defaults: { _controller: APITaskBundle:CompanyAttribute:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

company_attribute_delete:
    path:     /company-attributes/{id}
    defaults: { _controller: APITaskBundle:CompanyAttribute:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'