filter_list:
    path:     /filters
    defaults: { _controller: APITaskBundle:Filter:list }
    methods: [GET]

filter:
    path:     /filters/{id}
    defaults: { _controller: APITaskBundle:Filter:get }
    methods: [GET]
    requirements:
        id: '\d+'

filter_create:
    path:     /filters
    defaults: { _controller: APITaskBundle:Filter:create }
    methods: [POST]

filter_set_user_remembered:
    path:     /filters/{id}/user-remembered
    defaults: { _controller: APITaskBundle:Filter:setUsersRememberedFilter }
    methods: [PUT]
    requirements:
            id: '\d+'

filter_get_user_remembered:
    path:     /filters/user-remembered
    defaults: { _controller: APITaskBundle:Filter:getUsersRememberedFilter }
    methods: [GET]

filter_reset_user_remembered:
    path:     /filters/user-remembered/delete
    defaults: { _controller: APITaskBundle:Filter:resetUsersRememberedFilter }
    methods: [PUT]

filter_project_create:
    path:     /filters/project/{projectId}
    defaults: { _controller: APITaskBundle:Filter:createProjectsFilter }
    methods: [POST]
    requirements:
        projectId: '\d+'

filter_update:
    path:     /filters/{id}
    defaults: { _controller: APITaskBundle:Filter:update }
    methods: [PUT]
    requirements:
            id: '\d+'

filter_delete:
    path:     /filters/{id}
    defaults: { _controller: APITaskBundle:Filter:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'
