filter_list:
    path:     /filters
    defaults: { _controller: APITaskBundle:Filter/List:list }
    methods: [GET]

filter:
    path:     /filters/{id}
    defaults: { _controller: APITaskBundle:Filter/Get:get }
    methods: [GET]
    requirements:
        id: '\d+'

filter_create:
    path:     /filters
    defaults: { _controller: APITaskBundle:Filter/Create:create }
    methods: [POST]

filter_update:
    path:     /filters/{id}
    defaults: { _controller: APITaskBundle:Filter/Update:update }
    methods: [PUT]
    requirements:
            id: '\d+'

filter_set_user_remembered:
    path:     /filters/{id}/user-remembered
    defaults: { _controller: APITaskBundle:Filter:setUsersRememberedFilter }
    methods: [PUT]
    requirements:
            id: '\d+'

filter_get_user_remembered:
    path:     /filters/user-remembered
    defaults: { _controller: APITaskBundle:Filter:getUsersRememberedFilter }
    methods: [GET]

filter_reset_user_remembered:
    path:     /filters/user-remembered/delete
    defaults: { _controller: APITaskBundle:Filter:resetUsersRememberedFilter }
    methods: [PUT]

filter_inactivate:
    path:     /filters/{id}/inactivate
    defaults: { _controller: APITaskBundle:Filter/Inactivate:inactivate }
    methods: [PUT]
    requirements:
            id: '\d+'

filter_restore:
    path:     /filters/{id}/restore
    defaults: { _controller: APITaskBundle:Filter/Activate:activate }
    methods: [PUT]
    requirements:
            id: '\d+'

filter_delete:
    path:     /filters/{id}/delete
    defaults: { _controller: APITaskBundle:Filter/Delete:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'

filter_project_create:
    path:     /filters/project/{projectId}
    defaults: { _controller: APITaskBundle:Filter/CreateInProject:create }
    methods: [POST]
    requirements:
        projectId: '\d+'

filter_project_update:
    path:     /filters/{filterId}/project/{projectId}
    defaults: { _controller: APITaskBundle:Filter/UpdateInProject:update }
    methods: [PUT]
    requirements:
        filterId: '\d+'
        projectId: '\d+'
