imap_list:
    path:     /imap
    defaults: { _controller: APITaskBundle:Imap:list }
    methods: [GET]

imap:
    path:     /imap/{id}
    defaults: { _controller: APITaskBundle:Imap:get }
    methods: [GET]
    requirements:
        id: '\d+'

imap_create:
    path:     /imap
    defaults: { _controller: APITaskBundle:Imap:create }
    methods: [POST]

imap_update:
    path:     /imap/{id}
    defaults: { _controller: APITaskBundle:Imap:update }
    methods: [PUT]
    requirements:
            id: '\d+'

imap_partial_update:
    path:     /imap/{id}
    defaults: { _controller: APITaskBundle:Imap:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

imap_delete:
    path:     /imap/{id}
    defaults: { _controller: APITaskBundle:Imap:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'