imap_list:
    path:     /imap
    defaults: { _controller: APITaskBundle:Imap:list }
    methods: [GET]

imap:
    path:     /imap/{id}
    defaults: { _controller: APITaskBundle:Imap:get }
    methods: [GET]
    requirements:
        id: '\d+'

imap_create:
    path:     /imap/project/{projectId}
    defaults: { _controller: APITaskBundle:Imap:create }
    methods: [POST]
    requirements:
        projectId: '\d+'

imap_update:
    path:     /imap/{id}
    defaults: { _controller: APITaskBundle:Imap:update }
    methods: [PUT]
    requirements:
        id: '\d+'

imap_update_with_project:
    path:     /imap/{id}/project/{projectId}
    defaults: { _controller: APITaskBundle:Imap:update }
    methods: [PUT]
    requirements:
        id: '\d+'
        projectId: '\d+'

imap_inactivate:
    path:     /imap/{id}/inactivate
    defaults: { _controller: APITaskBundle:Imap:inactivate }
    methods: [PUT]
    requirements:
        id: '\d+'

imap_restore:
    path:     /imap/{id}/restore
    defaults: { _controller: APITaskBundle:Imap:restore }
    methods: [PUT]
    requirements:
        id: '\d+'

imap_delete:
    path:     /imap/{id}
    defaults: { _controller: APITaskBundle:Imap:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'