left_menu_param_list:
    path:     /left-menu-params
    defaults: { _controller: APITaskBundle:Main:getLeftNavigationParams }
    methods: [GET]

left_menu_param_list_from_date:
    path:     /left-menu-params/{date}
    defaults: { _controller: APITaskBundle:Main:getLeftNavigationParams }
    methods: [GET]
    requirements:
            date: '\d+'