users_notifications:
    path:     /notification
    defaults: { _controller: APITaskBundle:Notification:getLoggedUsersNotification}
    methods: [GET]

notification_set_as_read:
    path:     /notification/read/{read}
    defaults: { _controller: APITaskBundle:Notification:setAsReadNotification }
    methods: [PUT]

notification_delete:
    path:     /notification/{notificationId}
    defaults: { _controller: APITaskBundle:Notification:deleteNotification }
    methods: [DELETE]
    requirements:
            notificationId: '\d+'