projects_list:
    path:     /projects
    defaults: { _controller: APITaskBundle:Project:list }
    methods: [GET]

projects_list_where_logged_user_can_create_tasks:
    path:     /projects/create-tasks
    defaults: { _controller: APITaskBundle:Project:listOfProjectsWhereCanCreateTasksLoggedUser }
    methods: [GET]

project:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:get }
    methods: [GET]
    requirements:
        id: '\d+'

projects_create:
    path:     /projects
    defaults: { _controller: APITaskBundle:Project:create }
    methods: [POST]

projects_update:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:update }
    methods: [PUT]
    requirements:
            id: '\d+'

projects_partial_update:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

projects_delete:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'

projects_restore:
    path:     /projects/restore/{id}
    defaults: { _controller: APITaskBundle:Project:restore }
    methods: [PATCH]
    requirements:
            id: '\d+'

project_add_to_user:
    path:     /project/{projectId}/user/{userId}
    defaults: { _controller: APITaskBundle:Project:addUserToProject }
    methods: [POST]
    requirements:
            projectId: '\d+'
            userId: '\d+'

project_update_user_acl:
    path:     /project/{projectId}/user/{userId}
    defaults: { _controller: APITaskBundle:Project:updateUserProjectAcl }
    methods: [PUT]
    requirements:
            projectId: '\d+'
            userId: '\d+'

project_remove_from_user:
    path:     /project/{projectId}/user/{userId}
    defaults: { _controller: APITaskBundle:Project:removeUserFromProject }
    methods: [DELETE]
    requirements:
            projectId: '\d+'
            userId: '\d+'

project_process_users_acl:
    path:     /project/{projectId}/process-acl
    defaults: { _controller: APITaskBundle:Project:processProjectAclForUsers }
    methods: [POST]
    requirements:
            projectId: '\d+'

project_assigners:
    path:     /project/assigners/{projectId}
    defaults: { _controller: APITaskBundle:Project:getProjectAssigners }
    methods: [GET]
    requirements:
        projectId: '\d+'

task_without_project_assigners:
    path:     /project/assigners/task/{taskId}
    defaults: { _controller: APITaskBundle:Project:getProjectAssigners }
    methods: [GET]
    requirements:
        taskId: '\d+'