projects_list:
    path:     /projects
    defaults: { _controller: APITaskBundle:Project:list }
    methods: [GET]

projects_list_where_logged_user_can_create_tasks:
    path:     /projects/create-tasks
    defaults: { _controller: APITaskBundle:Project:listOfProjectsWhereCanCreateTasksLoggedUser }
    methods: [GET]

projects_list_where_logged_user_can_view_tasks:
    path:     /projects/view-tasks
    defaults: { _controller: APITaskBundle:Project:listOfProjectsWhereLoggedUserCanViewTasks }
    methods: [GET]

project:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:get }
    methods: [GET]
    requirements:
        id: '\d+'

projects_create:
    path:     /projects
    defaults: { _controller: APITaskBundle:Project:create }
    methods: [POST]

projects_update:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:update }
    methods: [PUT]
    requirements:
            id: '\d+'

projects_delete:
    path:     /projects/{id}/inactivate
    defaults: { _controller: APITaskBundle:Project:delete }
    methods: [PUT]
    requirements:
            id: '\d+'

projects_restore:
    path:     /projects/{id}/restore
    defaults: { _controller: APITaskBundle:Project:restore }
    methods: [PUT]
    requirements:
            id: '\d+'

project_add_to_user:
    path:     /project/{projectId}/user/{userId}/add
    defaults: { _controller: APITaskBundle:Project:addUserToProject }
    methods: [PUT]
    requirements:
            projectId: '\d+'
            userId: '\d+'

project_remove_from_user:
    path:     /project/{projectId}/user/{userId}/remove
    defaults: { _controller: APITaskBundle:Project:removeUserFromProject }
    methods: [PUT]
    requirements:
            projectId: '\d+'
            userId: '\d+'

project_process_users_acl:
    path:     /project/{projectId}/process-more-acl
    defaults: { _controller: APITaskBundle:Project:processProjectAclForMoreUsers }
    methods: [PUT]
    requirements:
            projectId: '\d+'

project_list_of_available_assign_users:
    path:     /project/{projectId}/assign-user
    defaults: { _controller: APITaskBundle:TaskParts/Assign:listOfAllAvailableAssigners}
    methods: [GET]
    requirements:
            projectId: '\d+'
