projects_list:
    path:     /projects
    defaults: { _controller: APITaskBundle:Project:list }
    methods: [GET]

project:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:get }
    methods: [GET]
    requirements:
        id: '\d+'

projects_create:
    path:     /projects
    defaults: { _controller: APITaskBundle:Project:create }
    methods: [POST]

projects_update:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:update }
    methods: [PUT]
    requirements:
            id: '\d+'

projects_partial_update:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

projects_delete:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'

projects_restore:
    path:     /projects/{id}
    defaults: { _controller: APITaskBundle:Project:restore }
    methods: [PATCH]
    requirements:
            id: '\d+'