status_list:
    path:     /status
    defaults: { _controller: APITaskBundle:Status:list }
    methods: [GET]

status:
    path:     /status/{id}
    defaults: { _controller: APITaskBundle:Status:get }
    methods: [GET]
    requirements:
        id: '\d+'

status_create:
    path:     /status
    defaults: { _controller: APITaskBundle:Status:create }
    methods: [POST]

status_update:
    path:     /status/{id}
    defaults: { _controller: APITaskBundle:Status:update }
    methods: [PUT]
    requirements:
            id: '\d+'

status_inactivate:
    path:     /status/{id}/inactivate
    defaults: { _controller: APITaskBundle:Status:delete }
    methods: [PUT]
    requirements:
            id: '\d+'

status_restore:
    path:     /status/{id}/restore
    defaults: { _controller: APITaskBundle:Status:restore }
    methods: [PUT]
    requirements:
            id: '\d+'