status_list:
    path:     /status
    defaults: { _controller: APITaskBundle:Status:list }
    methods: [GET]

status:
    path:     /status/{id}
    defaults: { _controller: APITaskBundle:Status:get }
    methods: [GET]
    requirements:
        id: '\d+'

status_create:
    path:     /status
    defaults: { _controller: APITaskBundle:Status:create }
    methods: [POST]

status_update:
    path:     /status/{id}
    defaults: { _controller: APITaskBundle:Status:update }
    methods: [PUT]
    requirements:
            id: '\d+'

status_partial_update:
    path:     /status/{id}
    defaults: { _controller: APITaskBundle:Status:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

status_delete:
    path:     /status/{id}
    defaults: { _controller: APITaskBundle:Status:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'