tasks_list:
    path:     /tasks
    defaults: { _controller: APITaskBundle:Task/List:list }
    methods: [GET]

tasks_list_saved_filter:
    path:     /tasks/filter/{filterId}
    defaults: { _controller: APITaskBundle:Task/ListFromFilter:list }
    methods: [GET]
    requirements:
        filterId: '\d+'

tasks_list_company_filter:
    path:     /tasks/filter/{filterId}/company/{companyId}
    defaults: { _controller: APITaskBundle:Task/ListCompanyFilter:list }
    methods: [GET]
    requirements:
        filterId: '\d+'
        companyId: '\d+'
task:
    path:     /tasks/{id}
    defaults: { _controller: APITaskBundle:TaskParts/Task:get }
    methods: [GET]
    requirements:
        id: '\d+'

tasks_list_of_tasks_repeating_tasks:
    path:     /tasks/{taskId}/repeating-task
    defaults: { _controller: APITaskBundle:TaskParts/RepeatingTask:list}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_create_project_status:
    path:     /tasks/project/{projectId}/status/{statusId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:create }
    methods: [POST]
    requirements:
            projectId: '\d+'
            statusId: '\d+'

tasks_create_project_status_requester:
    path:     /tasks/project/{projectId}/status/{statusId}/requester/{requesterId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:create }
    methods: [POST]
    requirements:
            projectId: '\d+'
            statusId: '\d+'
            requesterId: '\d+'

tasks_create_project_status_company:
    path:     /tasks/project/{projectId}/status/{statusId}/company/{companyId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:create }
    methods: [POST]
    requirements:
            projectId: '\d+'
            statusId: '\d+'
            companyId: '\d+'

tasks_create_project_status_requester_company:
    path:     /tasks/project/{projectId}/status/{statusId}/requester/{requesterId}/company/{companyId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:create }
    methods: [POST]
    requirements:
            projectId: '\d+'
            statusId: '\d+'
            requesterId: '\d+'
            companyId: '\d+'

tasks_update:
    path:     /tasks/{taskId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'

tasks_update_project:
    path:     /tasks/{taskId}/project/{projectId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            projectId: '\d+'

tasks_update_project_status:
    path:     /tasks/{taskId}/project/{projectId}/status/{statusId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            projectId: '\d+'
            statusId: '\d+'

tasks_update_project_status_requester:
    path:     /tasks/{taskId}/project/{projectId}/status/{statusId}/requester/{requesterId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            projectId: '\d+'
            statusId: '\d+'
            requesterId: '\d+'

tasks_update_project_status_requester_company:
    path:     /tasks/{taskId}/project/{projectId}/status/{statusId}/requester/{requesterId}/company/{companyId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            projectId: '\d+'
            statusId: '\d+'
            requesterId: '\d+'
            companyId: '\d+'

tasks_update_status:
    path:     /tasks/{taskId}/status/{statusId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            statusId: '\d+'

tasks_update_status_requester:
    path:     /tasks/{taskId}/status/{statusId}/requester/{requesterId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            statusId: '\d+'
            requesterId: '\d+'

tasks_update_status_requester_company:
    path:     /tasks/{taskId}/status/{statusId}/requester/{requesterId}/company/{companyId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            statusId: '\d+'
            requesterId: '\d+'
            companyId: '\d+'

tasks_update_requester:
    path:     /tasks/{taskId}/requester/{requesterId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            requesterId: '\d+'

tasks_update_requester_company:
    path:     /tasks/{taskId}/requester/{requesterId}/company/{companyId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            requesterId: '\d+'
            companyId: '\d+'

tasks_update_company:
    path:     /tasks/{taskId}/company/{companyId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:update }
    methods: [PUT]
    requirements:
            taskId: '\d+'
            companyId: '\d+'

tasks_delete:
    path:     /tasks/{taskId}
    defaults: { _controller: APITaskBundle:TaskParts/Task:delete }
    methods: [DELETE]
    requirements:
            taskId: '\d+'

tasks_list_of_tasks_followers:
    path:     /tasks/{taskId}/follower
    defaults: { _controller: APITaskBundle:TaskParts/Follower:listOfTasksFollowers}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_add_follower_to_task:
    path:     /tasks/{taskId}/add-follower/{userId}
    defaults: { _controller: APITaskBundle:TaskParts/Follower:addFollowerToTask}
    methods: [PUT]
    requirements:
            taskId: '\d+'
            userId: '\d+'

tasks_remove_follower_from_task:
    path:     /tasks/{taskId}/remove-follower/{userId}
    defaults: { _controller: APITaskBundle:TaskParts/Follower:removeFollowerFromTask}
    methods: [PUT]
    requirements:
            taskId: '\d+'
            userId: '\d+'

tasks_list_of_tasks_tags:
    path:     /tasks/{taskId}/tag
    defaults: { _controller: APITaskBundle:TaskParts/Tag:listOfTasksTags}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_add_tag_to_task:
    path:     /tasks/{taskId}/add-tag/{tagId}
    defaults: { _controller: APITaskBundle:TaskParts/Tag:addTagToTask}
    methods: [PUT]
    requirements:
            taskId: '\d+'
            tagId: '\d+'

tasks_remove_tag_from_task:
    path:     /tasks/{taskId}/remove-tag/{tagId}
    defaults: { _controller: APITaskBundle:TaskParts/Tag:removeTagFromTask}
    methods: [PUT]
    requirements:
            taskId: '\d+'
            tagId: '\d+'

tasks_assign_user_to_task:
    path:     /tasks/{taskId}/assign-user/{userId}
    defaults: { _controller: APITaskBundle:TaskParts/Assign:createAssignUserToTask}
    methods: [POST]
    requirements:
            taskId: '\d+'
            userId: '\d+'

tasks_assign_user_to_task_with_specific_status:
    path:     /tasks/{taskId}/assign-user/{userId}/status/{statusId}
    defaults: { _controller: APITaskBundle:TaskParts/Assign:createAssignUserToTask}
    methods: [POST]
    requirements:
            taskId: '\d+'
            userId: '\d+'
            statusId: '\d+'

tasks_update_assign_user_to_task:
    path:     /tasks/{taskId}/assign-user/{userId}/status/{statusId}
    defaults: { _controller: APITaskBundle:TaskParts/Assign:updateAssignUserToTask}
    methods: [PATCH]
    requirements:
            taskId: '\d+'
            userId: '\d+'
            statusId: '\d+'

tasks_remove_assign_user_from_task:
    path:     /tasks/{taskId}/assign-user/{userId}
    defaults: { _controller: APITaskBundle:TaskParts/Assign:removeAssignUserFromTask}
    methods: [DELETE]
    requirements:
            taskId: '\d+'
            userId: '\d+'

tasks_list_of_tasks_attachments:
    path:     /tasks/{taskId}/attachment
    defaults: { _controller: APITaskBundle:TaskParts/Attachment:listOfTasksAttachments}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_add_attachment_to_task:
    path:     /tasks/{taskId}/add-attachment/{slug}
    defaults: { _controller: APITaskBundle:TaskParts/Attachment:addAttachmentToTask}
    methods: [PUT]
    requirements:
            taskId: '\d+'

tasks_remove_attachment_from_task:
    path:     /tasks/{taskId}/remove-attachment/{slug}
    defaults: { _controller: APITaskBundle:TaskParts/Attachment:removeAttachmentFromTask}
    methods: [PUT]
    requirements:
            taskId: '\d+'

tasks_list_of_tasks_comments:
    path:     /tasks/{taskId}/comments
    defaults: { _controller: APITaskBundle:TaskParts/Comment:tasksCommentsList }
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_comment:
    path:     /tasks/comments/{commentId}
    defaults: { _controller: APITaskBundle:TaskParts/Comment:getTasksComment }
    methods: [GET]
    requirements:
            commentId: '\d+'

tasks_add_comment_to_task:
    path:     /tasks/{taskId}/add-comment
    defaults: { _controller: APITaskBundle:TaskParts/Comment:createTasksComment }
    methods: [POST]
    requirements:
            taskId: '\d+'

tasks_add_comment_to_comment:
    path:     /tasks/comments/{commentId}/add-comment
    defaults: { _controller: APITaskBundle:TaskParts/Comment:createCommentsComment }
    methods: [POST]
    requirements:
            commentId: '\d+'

tasks_delete_tasks_comment:
    path:     /tasks/comments/{commentId}
    defaults: { _controller: APITaskBundle:TaskParts/Comment:delete }
    methods: [DELETE]
    requirements:
            commentId: '\d+'

tasks_add_attachment_to_comment:
    path:     /tasks/comments/{commentId}/add-attachment/{slug}
    defaults: { _controller: APITaskBundle:TaskParts/CommentAttachment:addAttachmentToComment}
    methods: [PUT]
    requirements:
            commentId: '\d+'

tasks_remove_attachment_from_comment:
    path:     /tasks/comments/{commentId}/remove-attachment/{slug}
    defaults: { _controller: APITaskBundle:TaskParts/CommentAttachment:removeAttachmentFromComment}
    methods: [PUT]
    requirements:
            commentId: '\d+'

tasks_list_of_tasks_subtasks:
    path:     /tasks/{taskId}/subtasks
    defaults: { _controller: APITaskBundle:TaskParts/Subtask:listOfTasksSubtasks}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_create_subtask:
    path:     /tasks/{taskId}/subtask
    defaults: { _controller: APITaskBundle:TaskParts/Subtask:createSubtask}
    methods: [POST]
    requirements:
            taskId: '\d+'

tasks_update_subtask:
    path:     /tasks/{taskId}/subtask/{subtaskId}
    defaults: { _controller: APITaskBundle:TaskParts/Subtask:updateSubtask}
    methods: [PUT]
    requirements:
            taskId: '\d+'
            subtaskId: '\d+'

tasks_delete_subtask:
    path:     /tasks/{taskId}/subtask/{subtaskId}
    defaults: { _controller: APITaskBundle:TaskParts/Subtask:deleteSubtask}
    methods: [DELETE]
    requirements:
            taskId: '\d+'
            subtaskId: '\d+'