tasks_list:
    path:     /tasks
    defaults: { _controller: APITaskBundle:Task/Task:list }
    methods: [GET]

tasks_list_saved_filter:
    path:     /tasks/filter/{filterId}
    defaults: { _controller: APITaskBundle:Task/Task:listSavedFilter }
    methods: [GET]
    requirements:
        filterId: '\d+'

task:
    path:     /tasks/{id}
    defaults: { _controller: APITaskBundle:Task/Task:get }
    methods: [GET]
    requirements:
        id: '\d+'

tasks_create:
    path:     /tasks/project/{projectId}/user/{requestedUserId}
    defaults: { _controller: APITaskBundle:Task/Task:create }
    methods: [POST]

tasks_update:
    path:     /tasks/{id}/project/{projectId}/user/{requestedUserId}
    defaults: { _controller: APITaskBundle:Task/Task:update }
    methods: [PUT]
    requirements:
            id: '\d+'

tasks_partial_update:
    path:     /tasks/{id}/project/{projectId}/user/{requestedUserId}
    defaults: { _controller: APITaskBundle:Task/Task:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

tasks_delete:
    path:     /tasks/{id}
    defaults: { _controller: APITaskBundle:Task/Task:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'

tasks_list_of_tasks_followers:
    path:     /tasks/{taskId}/follower
    defaults: { _controller: APITaskBundle:Task/Follower:listOfTasksFollowers}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_add_follower_to_task:
    path:     /tasks/{taskId}/follower/{userId}
    defaults: { _controller: APITaskBundle:Task/Follower:addFollowerToTask}
    methods: [POST]
    requirements:
            taskId: '\d+'
            userId: '\d+'

tasks_remove_follower_from_task:
    path:     /tasks/{taskId}/follower/{userId}
    defaults: { _controller: APITaskBundle:Task/Follower:removeFollowerFromTask}
    methods: [PATCH]
    requirements:
            taskId: '\d+'
            userId: '\d+'

tasks_list_of_tasks_tags:
    path:     /tasks/{taskId}/tag
    defaults: { _controller: APITaskBundle:Task/Tag:listOfTasksTags}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_add_tag_to_task:
    path:     /tasks/{taskId}/tag/{tagId}
    defaults: { _controller: APITaskBundle:Task/Tag:addTagToTask}
    methods: [POST]
    requirements:
            taskId: '\d+'
            tagId: '\d+'

tasks_remove_tag_from_task:
    path:     /tasks/{taskId}/tag/{tagId}
    defaults: { _controller: APITaskBundle:Task/Tag:removeTagFromTask}
    methods: [PATCH]
    requirements:
            taskId: '\d+'
            tagId: '\d+'

tasks_list_of_tasks_assigned_users:
    path:     /tasks/{taskId}/assign-user
    defaults: { _controller: APITaskBundle:Task/Assign:listOfTasksAssignedUsers}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_assign_user_to_task:
    path:     /tasks/{taskId}/assign-user/{userId}
    defaults: { _controller: APITaskBundle:Task/Assign:createAssignUserToTask}
    methods: [POST]
    requirements:
            taskId: '\d+'
            userId: '\d+'

tasks_update_assign_user_to_task:
    path:     /tasks/{taskId}/assign-user/{userId}/status/{statusId}
    defaults: { _controller: APITaskBundle:Task/Assign:updateAssignUserToTask}
    methods: [PATCH]
    requirements:
            taskId: '\d+'
            userId: '\d+'
            statusId: '\d+'

tasks_remove_assign_user_from_task:
    path:     /tasks/{taskId}/assign-user/{userId}
    defaults: { _controller: APITaskBundle:Task/Assign:removeAssignUserFromTask}
    methods: [DELETE]
    requirements:
            taskId: '\d+'
            userId: '\d+'

tasks_list_of_tasks_attachments:
    path:     /tasks/{taskId}/attachment
    defaults: { _controller: APITaskBundle:Task/Attachment:listOfTasksAttachments}
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_add_attachment_to_task:
    path:     /tasks/{taskId}/attachment/{slug}
    defaults: { _controller: APITaskBundle:Task/Attachment:addAttachmentToTask}
    methods: [POST]
    requirements:
            taskId: '\d+'

tasks_remove_attachment_from_task:
    path:     /tasks/{taskId}/attachment/{slug}
    defaults: { _controller: APITaskBundle:Task/Attachment:removeAttachmentFromTask}
    methods: [DELETE]
    requirements:
            taskId: '\d+'

tasks_list_of_tasks_comments:
    path:     /tasks/{taskId}/comments
    defaults: { _controller: APITaskBundle:Task/Comment:tasksCommentsList }
    methods: [GET]
    requirements:
            taskId: '\d+'

tasks_comment:
    path:     /tasks/comments/{commentId}
    defaults: { _controller: APITaskBundle:Task/Comment:getTasksComment }
    methods: [GET]
    requirements:
            commentId: '\d+'

tasks_add_comment_to_task:
    path:     /tasks/{taskId}/comments
    defaults: { _controller: APITaskBundle:Task/Comment:createTasksComment }
    methods: [POST]
    requirements:
            taskId: '\d+'

tasks_add_comment_to_comment:
    path:     /tasks/comments/{commentId}
    defaults: { _controller: APITaskBundle:Task/Comment:createCommentsComment }
    methods: [POST]
    requirements:
            commentId: '\d+'

tasks_delete_tasks_comment:
    path:     /tasks/comments/{commentId}
    defaults: { _controller: APITaskBundle:Task/Comment:delete }
    methods: [DELETE]
    requirements:
            commentId: '\d+'


tasks_list_of_comments_attachments:
    path:     /tasks/comments/{commentId}/attachment
    defaults: { _controller: APITaskBundle:Task/CommentAttachment:listOfCommentsAttachments}
    methods: [GET]
    requirements:
            commentId: '\d+'

tasks_add_attachment_to_comment:
    path:     /tasks/comments/{commentId}/attachment/{slug}
    defaults: { _controller: APITaskBundle:Task/CommentAttachment:addAttachmentToComment}
    methods: [POST]
    requirements:
            commentId: '\d+'

tasks_remove_attachment_from_comment:
    path:     /tasks/comments/{commentId}/attachment/{slug}
    defaults: { _controller: APITaskBundle:Task/CommentAttachment:removeAttachmentFromComment}
    methods: [DELETE]
    requirements:
            commentId: '\d+'