unit_list:
    path:     /units
    defaults: { _controller: APITaskBundle:Unit:list }
    methods: [GET]

unit_list_of_all_units:
    path:     /units/all
    defaults: { _controller: APITaskBundle:Unit:listOfAllAvailableUnits}
    methods: [GET]

unit:
    path:     /units/{id}
    defaults: { _controller: APITaskBundle:Unit:get }
    methods: [GET]
    requirements:
        id: '\d+'

unit_create:
    path:     /units
    defaults: { _controller: APITaskBundle:Unit:create }
    methods: [POST]

unit_update:
    path:     /units/{id}
    defaults: { _controller: APITaskBundle:Unit:update }
    methods: [PUT]
    requirements:
            id: '\d+'

unit_restore:
    path:     /units/{id}/restore
    defaults: { _controller: APITaskBundle:Unit:restore }
    methods: [PUT]
    requirements:
            id: '\d+'

unit_inactivate:
    path:     /units/{id}/inactivate
    defaults: { _controller: APITaskBundle:Unit:delete }
    methods: [PUT]
    requirements:
            id: '\d+'