user_role_list:
    path:     /user-roles
    defaults: { _controller: APITaskBundle:UserRole:list }
    methods: [GET]

user_role:
    path:     /user-roles/{id}
    defaults: { _controller: APITaskBundle:UserRole:get }
    methods: [GET]
    requirements:
        id: '\d+'

user_role_create:
    path:     /user-roles
    defaults: { _controller: APITaskBundle:UserRole:create }
    methods: [POST]

user_role_update:
    path:     /user-roles/{id}
    defaults: { _controller: APITaskBundle:UserRole:update }
    methods: [PUT]
    requirements:
            id: '\d+'

user_role_partial_update:
    path:     /user-roles/{id}
    defaults: { _controller: APITaskBundle:UserRole:updatePartial }
    methods: [PATCH]
    requirements:
            id: '\d+'

user_role_delete:
    path:     /user-roles/{id}
    defaults: { _controller: APITaskBundle:UserRole:delete }
    methods: [DELETE]
    requirements:
            id: '\d+'