user_role_list:
    path:     /user-roles
    defaults: { _controller: APITaskBundle:UserRole:list }
    methods: [GET]

user_role:
    path:     /user-roles/{id}
    defaults: { _controller: APITaskBundle:UserRole:get }
    methods: [GET]
    requirements:
        id: '\d+'

user_role_create:
    path:     /user-roles
    defaults: { _controller: APITaskBundle:UserRole:create }
    methods: [POST]

user_role_update:
    path:     /user-roles/{id}
    defaults: { _controller: APITaskBundle:UserRole:update }
    methods: [PUT]
    requirements:
            id: '\d+'

user_role_inactivate:
    path:     /user-roles/{id}/inactivate
    defaults: { _controller: APITaskBundle:UserRole:delete }
    methods: [PUT]
    requirements:
            id: '\d+'

user_role_restore:
    path:     /user-roles/{id}/restore
    defaults: { _controller: APITaskBundle:UserRole:restore }
    methods: [PUT]
    requirements:
            id: '\d+'