<?php

namespace API\TaskBundle\Repository;

/**
 * CommentHasAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentHasAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
