<?php

namespace API\TaskBundle\Repository;

/**
 * CompanyDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyDataRepository extends \Doctrine\ORM\EntityRepository
{
}
