<?php

namespace API\TaskBundle\Repository;

/**
 * CompanyAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
