<?php

namespace API\TaskBundle\Repository;

/**
 * ImapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImapRepository extends \Doctrine\ORM\EntityRepository
{
}
