<?php

namespace API\TaskBundle\Repository;
use API\TaskBundle\Entity\Task;
use Doctrine\ORM\EntityRepository;

/**
 * InvoiceableItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceableItemRepository extends EntityRepository
{
    /**
     * @param Task $task
     * @return array
     */
    public function getAllEntities(Task $task):array
    {
        return [];
    }
}
