<?php

namespace API\TaskBundle\Repository;

use API\TaskBundle\Entity\InvoiceableItem;
use API\TaskBundle\Entity\Task;
use Doctrine\ORM\EntityRepository;

/**
 * InvoiceableItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceableItemRepository extends EntityRepository
{
    /**
     * @param Task $task
     * @return array
     */
    public function getAllEntities(Task $task):array
    {
        $query = $this->createQueryBuilder('invoiceableItem')
            ->select('invoiceableItem, unit')
            ->leftJoin('invoiceableItem.unit', 'unit')
            ->where('invoiceableItem.task = :task')
            ->setParameter('task', $task);

        return $query->getQuery()->getArrayResult();
    }

    /**
     * @param int $invoiceableItem
     * @return array
     */
    public function getEntity(int $invoiceableItem)
    {
        $query = $this->createQueryBuilder('invoiceableItem')
            ->select('invoiceableItem, unit')
            ->leftJoin('invoiceableItem.unit', 'unit')
            ->where('invoiceableItem.id = :invoiceableItem')
            ->setParameter('invoiceableItem', $invoiceableItem);

        return $query->getQuery()->getArrayResult();
    }
}
