<?php

namespace API\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RepeatingTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepeatingTaskRepository extends EntityRepository
{
    /**
     * @param array $options
     * @param array|bool $allowedTasks
     * @return array
     */
    public function getAllEntities(array $options, $allowedTasks): array
    {
        
        return [
            'array' => [],
            'count' => 10
        ];

    }
}
