<?php

namespace API\TaskBundle\Repository;

/**
 * RepeatingTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepeatingTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
