<?php

namespace API\TaskBundle\Repository;

/**
 * SmtpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmtpRepository extends \Doctrine\ORM\EntityRepository
{
}
