<?php

namespace API\TaskBundle\Repository;

use API\TaskBundle\Entity\Status;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{
    const LIMIT = 10;

    /**
     * Return's all entities with specific conditions based on actual Entity
     *
     * @param int $page
     * @param array $options
     * @return mixed
     */
    public function getAllEntities(int $page, array $options = [])
    {
        $isActive = $options['isActive'];
        $order = $options['order'];
        $limit = $options['limit'];

        if ('true' === $isActive || 'false' === $isActive) {
            if ($isActive === 'true') {
                $isActiveParam = 1;
            } else {
                $isActiveParam = 0;
            }
            $query = $this->createQueryBuilder('s')
                ->select('s')
                ->where('s.is_active = :isActiveParam')
                ->orderBy('s.order', $order)
                ->setParameter('isActiveParam', $isActiveParam)
                ->getQuery();
        } else {
            $query = $this->createQueryBuilder('s')
                ->select('s')
                ->orderBy('s.order', $order)
                ->getQuery();
        }

        if (999 !== $limit) {
            // Pagination
            if (1 < $page) {
                $query->setFirstResult($limit * $page - $limit);
            } else {
                $query->setFirstResult(0);
            }

            $query->setMaxResults($limit);

            $paginator = new Paginator($query, $fetchJoinCollection = true);
            $count = $paginator->count();

            return [
                'count' => $count,
                'array' => $this->formatData($paginator)
            ];
        }else {
            // Return all entities
            return [
                'array' => $this->formatData($query->getArrayResult(), true)
            ];
        }
    }

    /**
     * @param int $id
     * @return array
     */
    public function getEntity(int $id): array
    {
        $query = $this->createQueryBuilder('s')
            ->select()
            ->where('s.id = :sId')
            ->setParameter('sId', $id)
            ->getQuery();

        return $this->processData($query->getSingleResult());
    }

    /**
     * @return array
     */
    public function getAllStatusEntitiesWithIdAndTitle()
    {
        $query = $this->createQueryBuilder('s')
            ->select('s.id,s.title, s.color')
            ->where('s.is_active = :isActive')
            ->setParameter('isActive', true)
            ->getQuery();

        return $query->getArrayResult();
    }

    /**
     * @param $date
     * @return array
     */
    public function getAllStatusEntitiesForSelectionLists($date): array
    {
        if ($date) {
            $query = $this->createQueryBuilder('status')
                ->select('status.title, status.color, status.order, status.function, status.is_active')
                ->orderBy('status.order', 'ASC')
                ->where('status.updatedAt >= :date')
                ->setParameters([
                    'date' => $date
                ]);
        } else {
            $query = $this->createQueryBuilder('status')
                ->select('status.title, status.color, status.order, status.function, status.is_active')
                ->orderBy('status.order', 'ASC')
                ->where('status.is_active = :isActive')
                ->setParameter('isActive', true);
        }

        return $query->getQuery()->getArrayResult();
    }

    /**
     * @param $paginatorData
     * @param bool $array
     * @return array
     */
    private function formatData($paginatorData, $array = false):array
    {
        $response = [];
        foreach ($paginatorData as $data) {
            if ($array) {
                $response[] = $this->processArrayData($data);
            } else {
                $response[] = $this->processData($data);
            }
        }

        return $response;
    }

    /**
     * @param Status $data
     * @return array
     */
    private function processData(Status $data):array
    {
        $response = [
            'id' => $data->getId(),
            'title' => $data->getTitle(),
            'color' => $data->getColor(),
            'description' => $data->getDescription(),
            'order' => $data->getOrder(),
            'is_active' => $data->getIsActive(),
            'default' => $data->getDefault(),
            'function' => $data->getFunction()
        ];

        return $response;
    }

    /**
     * @param array $data
     * @return array
     */
    private function processArrayData(array $data): array
    {
        $response = [
            'id' => $data['id'],
            'title' => $data['title'],
            'color' => $data['color'],
            'description' => $data['description'],
            'order' => $data['order'],
            'is_active' => $data['is_active'],
            'default' => $data['default'],
            'function' => $data['function']
        ];

        return $response;
    }
}
