<?php

namespace API\TaskBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * Return all User's Tags
     *
     * @param int $userId
     * @return array
     */
    public function getTags(int $userId)
    {
        $query = $this->createQueryBuilder('t')
            ->where('t.user = :userId')
            ->setParameter('userId',$userId);

        return $query->getQuery()->getArrayResult();
    }
}
