<?php

namespace API\TaskBundle\Repository;

use API\TaskBundle\Entity\TaskHasAttachment;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TaskHasAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskHasAttachmentRepository extends EntityRepository
{
    /**
     * Return's all entities with specific conditions based on actual Entity
     *
     * @param int $taskId
     * @param int $page
     * @param int $limit
     * @return array|null
     */
    public function getAllAttachmentSlugs(int $taskId, int $page, int $limit)
    {
        $query = $this->createQueryBuilder('tha')
            ->select('tha')
            ->leftJoin('tha.task', 'task')
            ->orderBy('tha.id', 'DESC')
            ->where('task.id = :taskId')
            ->setParameter('taskId', $taskId);

        if (999 !== $limit) {
            // Pagination
            if (1 < $page) {
                $query->setFirstResult($limit * $page - $limit);
            } else {
                $query->setFirstResult(0);
            }

            $query->setMaxResults($limit);

            $paginator = new Paginator($query, $fetchJoinCollection = true);
            $count = $paginator->count();

            return [
                'count' => $count,
                'array' => $this->formatData($paginator)
            ];
        } else {
            // Return all entities
            return [
                'array' => $this->formatData($query->getQuery()->getArrayResult(), true)
            ];
        }
    }

    /**
     * @param $paginatorData
     * @param bool $array
     * @return array
     */
    private function formatData($paginatorData, $array = false): array
    {
        $response = [];
        foreach ($paginatorData as $data) {
            if ($array) {
                $response[] = $this->processArrayData($data);
            } else {
                $response[] = $this->processData($data);
            }
        }

        return $response;
    }


    /**
     * @param TaskHasAttachment $data
     * @return array
     */
    private function processData(TaskHasAttachment $data): array
    {
        return [
            'slug' => $data->getSlug()
        ];
    }

    /**
     * @param array $data
     * @return array
     */
    private function processArrayData(array $data): array
    {
        return [
            'slug' => $data['slug']
        ];
    }
}
