<?php

namespace API\TaskBundle\Repository;

/**
 * TaskDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskDataRepository extends \Doctrine\ORM\EntityRepository
{
}
