<?php

namespace API\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskHasAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskHasAttachmentRepository extends EntityRepository
{
    /**
     * Return's all entities with specific conditions based on actual Entity
     *
     * @param int $page
     * @param int $taskId
     * @return array|null
     */
    public function getAllAttachmentSlugs(int $taskId, int $page)
    {
        $query = $this->createQueryBuilder('tha')
            ->select('tha.slug')
            ->where('tha.task = :taskId')
            ->setParameter('taskId', $taskId);

        $query->setMaxResults(TaskRepository::LIMIT);

        // Pagination calculating offset
        if (1 < $page) {
            $query->setFirstResult(TaskRepository::LIMIT * $page - TaskRepository::LIMIT);
        }

        return $query->getQuery()->getArrayResult();
    }

    /**
     * Return count of all Entities
     *
     * @param int $taskId
     * @return int
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \Doctrine\ORM\NoResultException
     * @internal param array $options
     *
     */
    public function countAttachmentEntities(int $taskId)
    {
        $query = $this->createQueryBuilder('tha')
            ->select('COUNT(tha.id)')
            ->where('tha.task = :taskId')
            ->setParameter('taskId', $taskId);

        return $query->getQuery()->getSingleScalarResult();
    }
}
