<?php

namespace API\TaskBundle\Repository;

/**
 * TaskAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
