<?php

namespace API\TaskBundle\Repository;

/**
 * TaskHasAssignedUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskHasAssignedUserRepository extends \Doctrine\ORM\EntityRepository
{
}
