<?php

namespace API\TaskBundle\Repository;

/**
 * TaskSubtaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskSubtaskRepository extends \Doctrine\ORM\EntityRepository
{
}
