<?php

namespace API\TaskBundle\Repository;

/**
 * TaskHasAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskHasAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
