<?php

namespace API\TaskBundle\Repository;

/**
 * UserHasProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
