<?php

namespace API\TaskBundle\Repository;

/**
 * UserHasTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasTagRepository extends \Doctrine\ORM\EntityRepository
{
}
